
package frontend;

import archivos.ManejoArchivos;
import gestionApuestas.ControlApuestas;
import gestionApuestas.ListaApostadores;
import gestionApuestas.Participante;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CIROSS
 */
public class IngresoApuestas extends javax.swing.JFrame {

    private ControlApuestas apuesta = new ControlApuestas();
    ListaApostadores lista;
    DefaultTableModel modeloTabla = new DefaultTableModel(); 
    /**
     * Creates new form IngresoApuestas
     */
    public IngresoApuestas() {
        initComponents();
        setLocationRelativeTo(null);
        lista = apuesta.getApostadores();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableApuestas = new javax.swing.JTable();
        jButtonArchivo = new javax.swing.JButton();
        jButtonManual = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuCierre = new javax.swing.JMenu();
        jMenuItemVerificarYCierre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableApuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableApuestas.setOpaque(false);
        jScrollPane1.setViewportView(jTableApuestas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 58, 925, -1));

        jButtonArchivo.setText("Agregar apuestas desde archivo");
        jButtonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 492, -1, -1));

        jButtonManual.setText("Agregar apuestas manualmente");
        jButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 492, -1, -1));

        jLabelTitulo.setText("APUESTAS INGRESADAS:");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 30, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(204, 204, 255));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -30, 1010, 560));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenuInicio.setText("Ir a Inicio");
        jMenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInicioActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuInicio);

        jMenuCierre.setText("Cierre de Apuestas");

        jMenuItemVerificarYCierre.setText("Cerrar y verificar apuestas");
        jMenuItemVerificarYCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerificarYCierreActionPerformed(evt);
            }
        });
        jMenuCierre.add(jMenuItemVerificarYCierre);

        jMenuBar1.add(jMenuCierre);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTabla() {
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Monto");
        modeloTabla.addColumn("1o.");
        modeloTabla.addColumn("2o.");
        modeloTabla.addColumn("3o.");
        modeloTabla.addColumn("4o.");
        modeloTabla.addColumn("5o.");
        modeloTabla.addColumn("6o.");
        modeloTabla.addColumn("7o.");
        modeloTabla.addColumn("8o.");
        modeloTabla.addColumn("9o.");
        modeloTabla.addColumn("10o.");

        this.jTableApuestas.setModel(modeloTabla);
    }
    
    private void jMenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInicioActionPerformed
        VistaPrincipal vp = new VistaPrincipal();
        vp.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_jMenuInicioActionPerformed

    private void jButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualActionPerformed
        IngresoIndividual ingreso = new IngresoIndividual();
        ingreso.setVisible(true);
    }//GEN-LAST:event_jButtonManualActionPerformed

    private void jButtonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArchivoActionPerformed
        
        ManejoArchivos.abrirArchivo(this,apuesta);
        
        Participante p = lista.getRaiz();        
        //ini
        lista.listar();
        //fin
        insertarParticipante(lista.getRaiz());
        
    }//GEN-LAST:event_jButtonArchivoActionPerformed

    private void jMenuItemVerificarYCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerificarYCierreActionPerformed
        apuesta.verificarSimple();
    }//GEN-LAST:event_jMenuItemVerificarYCierreActionPerformed

    public void insertarParticipante(Participante participante) {
        
        if (participante != null) {
            modeloTabla.addRow(participante.getArray());
            insertarParticipante(participante.getSiguiente());
        }
    }
    
    public void insertarUltimo() {
        Participante participante = lista.getUltimo();
        System.out.println(participante);
        insertarParticipante(participante);
        actualizarTabla();
        //modeloTabla.addRow(participante.getArray());
        
    }

    public ControlApuestas getApuesta() {
        return apuesta;
    }

    public void setApuesta(ControlApuestas apuesta) {
        this.apuesta = apuesta;
    }

    @Override
    public void dispose() {
        ActionEvent evt = null;
        jMenuInicioActionPerformed(evt);
    }
    
    public void actualizarTabla() {
        
        Participante participante = lista.getRaiz();
        
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            modeloTabla.setValueAt(participante.getNombre(), i, 0);
            modeloTabla.setValueAt(participante.getMonto(), i, 1);
            modeloTabla.setValueAt(participante.getOrden()[0], i, 2);
            modeloTabla.setValueAt(participante.getOrden()[1], i, 3);
            modeloTabla.setValueAt(participante.getOrden()[2], i, 4);
            modeloTabla.setValueAt(participante.getOrden()[3], i, 5);
            modeloTabla.setValueAt(participante.getOrden()[4], i, 6);
            modeloTabla.setValueAt(participante.getOrden()[5], i, 7);
            modeloTabla.setValueAt(participante.getOrden()[6], i, 8);
            modeloTabla.setValueAt(participante.getOrden()[7], i, 9);
            modeloTabla.setValueAt(participante.getOrden()[8], i, 10);
            modeloTabla.setValueAt(participante.getOrden()[9], i, 11);
            
        }

    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArchivo;
    private javax.swing.JButton jButtonManual;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCierre;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemVerificarYCierre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableApuestas;
    // End of variables declaration//GEN-END:variables
}
