
package frontend;

import gestionApuestas.ControlApuestas;
import gestionApuestas.Participante;
import javax.swing.JOptionPane;

/**
 *
 * @author CIROSS
 */
public class IngresoIndividual extends javax.swing.JFrame {

    /**
     * Creates new form IngresoIndividual
     */
    public IngresoIndividual() {
        initComponents();
        setLocationRelativeTo(null);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatos = new javax.swing.JPanel();
        jLabel1ro = new javax.swing.JLabel();
        jTextField1ro = new javax.swing.JTextField();
        jLabel6to = new javax.swing.JLabel();
        jTextField6to = new javax.swing.JTextField();
        jLabel2do = new javax.swing.JLabel();
        jTextField2do = new javax.swing.JTextField();
        jLabel7mo = new javax.swing.JLabel();
        jTextField7mo = new javax.swing.JTextField();
        jLabel3ro = new javax.swing.JLabel();
        jTextField3ro = new javax.swing.JTextField();
        jLabel8vo = new javax.swing.JLabel();
        jTextField8vo = new javax.swing.JTextField();
        jLabel4to = new javax.swing.JLabel();
        jTextField4to = new javax.swing.JTextField();
        jLabel9no = new javax.swing.JLabel();
        jTextField9no = new javax.swing.JTextField();
        jLabel5to = new javax.swing.JLabel();
        jTextField5to = new javax.swing.JTextField();
        jLabel10mo = new javax.swing.JLabel();
        jTextField10mo = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelMonto = new javax.swing.JLabel();
        jTextFieldMonto = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelDatos.setOpaque(false);
        jPanelDatos.setLayout(new java.awt.GridLayout(5, 4));

        jLabel1ro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1ro.setText("1ro. ");
        jPanelDatos.add(jLabel1ro);
        jPanelDatos.add(jTextField1ro);

        jLabel6to.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6to.setText("6to. ");
        jPanelDatos.add(jLabel6to);
        jPanelDatos.add(jTextField6to);

        jLabel2do.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2do.setText("2do. ");
        jPanelDatos.add(jLabel2do);
        jPanelDatos.add(jTextField2do);

        jLabel7mo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7mo.setText("7mo. ");
        jPanelDatos.add(jLabel7mo);
        jPanelDatos.add(jTextField7mo);

        jLabel3ro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3ro.setText("3ro. ");
        jPanelDatos.add(jLabel3ro);
        jPanelDatos.add(jTextField3ro);

        jLabel8vo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8vo.setText("8vo. ");
        jPanelDatos.add(jLabel8vo);
        jPanelDatos.add(jTextField8vo);

        jLabel4to.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4to.setText(" 4to. ");
        jPanelDatos.add(jLabel4to);
        jPanelDatos.add(jTextField4to);

        jLabel9no.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9no.setText("9no. ");
        jPanelDatos.add(jLabel9no);
        jPanelDatos.add(jTextField9no);

        jLabel5to.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5to.setText("5to. ");
        jPanelDatos.add(jLabel5to);
        jPanelDatos.add(jTextField5to);

        jLabel10mo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10mo.setText("10mo. ");
        jPanelDatos.add(jLabel10mo);
        jPanelDatos.add(jTextField10mo);

        getContentPane().add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 159, 397, 222));

        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 50, -1, -1));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 41, 282, 35));

        jLabelMonto.setText("Monto:");
        getContentPane().add(jLabelMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 112, -1, 35));
        getContentPane().add(jTextFieldMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 112, 282, 35));

        jButtonAgregar.setText("Agregar apuesta");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 399, -1, -1));

        jButton2.setText("Salir");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 399, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(204, 204, 255));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 510, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        
        if(jTextFieldNombre.getText().equals("") || jTextFieldMonto.getText().equals("") || jTextField1ro.getText().equals("") || jTextField2do.getText().equals("") 
            || jTextField3ro.getText().equals("") || jTextField4to.getText().equals("") || jTextField5to.getText().equals("") || jTextField6to.getText().equals("") 
            || jTextField7mo.getText().equals("") || jTextField8vo.getText().equals("") || jTextField9no.getText().equals("") || jTextField10mo.getText().equals("")) {
            
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
            
        } else {
            
            String[] datos = {jTextFieldNombre.getText(),jTextFieldMonto.getText(),jTextField1ro.getText(),jTextField2do.getText(),jTextField3ro.getText(),jTextField4to.getText(),
                            jTextField5to.getText(),jTextField6to.getText(),jTextField7mo.getText(),jTextField8vo.getText(),jTextField9no.getText(),jTextField10mo.getText()};
            
            ControlApuestas apuestas = new ControlApuestas();
            apuestas.ingresarApuesta(datos);
            
            //Participante participante = apuestas.getApostadores().getUltimo();
            
            IngresoApuestas ingresoApuestas = new IngresoApuestas();
            ingresoApuestas.insertarUltimo();
            //ingresoApuestas.insertarParticipante(participante);
            JOptionPane.showMessageDialog(this, "Apuesta agregada");
            limpiarCampos();
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void limpiarCampos() {
        jTextFieldNombre.setText("");
        jTextFieldMonto.setText("");
        jTextField1ro.setText("");
        jTextField2do.setText("");
        jTextField3ro.setText("");
        jTextField4to.setText("");
        jTextField5to.setText("");
        jTextField6to.setText("");
        jTextField7mo.setText("");
        jTextField8vo.setText("");
        jTextField9no.setText("");
        jTextField10mo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JLabel jLabel10mo;
    private javax.swing.JLabel jLabel1ro;
    private javax.swing.JLabel jLabel2do;
    private javax.swing.JLabel jLabel3ro;
    private javax.swing.JLabel jLabel4to;
    private javax.swing.JLabel jLabel5to;
    private javax.swing.JLabel jLabel6to;
    private javax.swing.JLabel jLabel7mo;
    private javax.swing.JLabel jLabel8vo;
    private javax.swing.JLabel jLabel9no;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JTextField jTextField10mo;
    private javax.swing.JTextField jTextField1ro;
    private javax.swing.JTextField jTextField2do;
    private javax.swing.JTextField jTextField3ro;
    private javax.swing.JTextField jTextField4to;
    private javax.swing.JTextField jTextField5to;
    private javax.swing.JTextField jTextField6to;
    private javax.swing.JTextField jTextField7mo;
    private javax.swing.JTextField jTextField8vo;
    private javax.swing.JTextField jTextField9no;
    private javax.swing.JTextField jTextFieldMonto;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

}
