
package frontend;

import gestionApuestas.ControlApuestas;
import gestionApuestas.ListaApostadores;
import gestionApuestas.Participante;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CIROSS
 */
public class Resultados extends javax.swing.JFrame {

    private ControlApuestas apuesta = new ControlApuestas();
    ListaApostadores lista;
    DefaultTableModel modeloTabla = new DefaultTableModel(); 
    /**
     * Creates new form Resultados
     */
    public Resultados() {
        initComponents();
        setLocationRelativeTo(null);
        lista = apuesta.getApuestasAprobadas();
        inicializarTabla();
    }
    
    private void inicializarTabla() {
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Monto");
        modeloTabla.addColumn("1o.");
        modeloTabla.addColumn("2o.");
        modeloTabla.addColumn("3o.");
        modeloTabla.addColumn("4o.");
        modeloTabla.addColumn("5o.");
        modeloTabla.addColumn("6o.");
        modeloTabla.addColumn("7o.");
        modeloTabla.addColumn("8o.");
        modeloTabla.addColumn("9o.");
        modeloTabla.addColumn("10o.");
        modeloTabla.addColumn("Punteo");

        this.jTable1.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion = new javax.swing.JLabel();
        jTextField1ro = new javax.swing.JTextField();
        jTextField2do = new javax.swing.JTextField();
        jTextField3ro = new javax.swing.JTextField();
        jTextField4to = new javax.swing.JTextField();
        jTextField5to = new javax.swing.JTextField();
        jTextField6to = new javax.swing.JTextField();
        jTextField7mo = new javax.swing.JTextField();
        jTextField8vo = new javax.swing.JTextField();
        jTextField9no = new javax.swing.JTextField();
        jTextField10mo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1ro = new javax.swing.JLabel();
        jLabel2do = new javax.swing.JLabel();
        jLabel3ro = new javax.swing.JLabel();
        jLabel4to = new javax.swing.JLabel();
        jLabel5to = new javax.swing.JLabel();
        jLabel6to = new javax.swing.JLabel();
        jLabel7mo = new javax.swing.JLabel();
        jLabel8vo = new javax.swing.JLabel();
        jLabel9no = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelGanador = new javax.swing.JLabel();
        jTextField1Ganador = new javax.swing.JTextField();
        jButtonOrdenarPuntos = new javax.swing.JButton();
        jButtonOrdenarNombre = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelTitulo.setText("RESULTADOS:");

        jLabelInstruccion.setText("Ingrese el orden en que finalizó la carrera");

        jTextField8vo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8voActionPerformed(evt);
            }
        });

        jScrollPane1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Monto", "1o.", "2o.", "3o.", "4o.", "5o.", "6o.", "7o.", "8o.", "9o.", "10o.", "Puntaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(10).setResizable(false);
            jTable1.getColumnModel().getColumn(11).setResizable(false);
            jTable1.getColumnModel().getColumn(12).setResizable(false);
        }

        jLabel1ro.setText("1er. Lugar");

        jLabel2do.setText("2do. Lugar");

        jLabel3ro.setText("3er. Lugar");

        jLabel4to.setText("4to. Lugar");

        jLabel5to.setText("5to. Lugar");

        jLabel6to.setText("6to.. Lugar");

        jLabel7mo.setText("7mo. Lugar");

        jLabel8vo.setText("8vo. Lugar");

        jLabel9no.setText("9no. Lugar");

        jLabel10.setText("10mo. Lugar");

        jLabelGanador.setText("GANADOR:");

        jTextField1Ganador.setEditable(false);
        jTextField1Ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1GanadorActionPerformed(evt);
            }
        });

        jButtonOrdenarPuntos.setText("Ordenar por Puntuacion");
        jButtonOrdenarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPuntosActionPerformed(evt);
            }
        });

        jButtonOrdenarNombre.setText("Ordenar por Nombre");
        jButtonOrdenarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarNombreActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 403, Short.MAX_VALUE)
                        .addComponent(jLabelGanador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelInstruccion)
                            .addComponent(jLabelTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9no)
                                            .addComponent(jLabel8vo)
                                            .addComponent(jLabel7mo)
                                            .addComponent(jLabel6to)
                                            .addComponent(jLabel5to)
                                            .addComponent(jLabel4to)
                                            .addComponent(jLabel3ro)
                                            .addComponent(jLabel2do)
                                            .addComponent(jLabel1ro))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField1ro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField2do, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField3ro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField4to, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField5to, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField6to, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField7mo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField8vo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField9no, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField10mo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonValidar)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOrdenarPuntos)
                                .addGap(133, 133, 133)
                                .addComponent(jButtonOrdenarNombre)
                                .addGap(210, 210, 210))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTitulo)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelInstruccion)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1ro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1ro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2do, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2do))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3ro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3ro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4to))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5to))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6to))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7mo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7mo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8vo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8vo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10mo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonValidar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGanador)
                            .addComponent(jTextField1Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonOrdenarPuntos)
                            .addComponent(jButtonOrdenarNombre))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar.setBackground(new java.awt.Color(204, 204, 255));

        jMenuInicio.setText("Ir a Inicio");
        jMenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInicioActionPerformed(evt);
            }
        });
        jMenuBar.add(jMenuInicio);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOrdenarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPuntosActionPerformed
        apuesta.ordenarPuntos();
        actualizarTabla();
    }//GEN-LAST:event_jButtonOrdenarPuntosActionPerformed

    private void jButtonOrdenarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOrdenarNombreActionPerformed

    private void jTextField8voActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8voActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8voActionPerformed

    private void jMenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInicioActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuInicioActionPerformed

    private void jTextField1GanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1GanadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1GanadorActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        if(jTextField1ro.getText().equals("") || jTextField2do.getText().equals("") || jTextField3ro.getText().equals("") || jTextField4to.getText().equals("")  
            || jTextField5to.getText().equals("") || jTextField6to.getText().equals("") || jTextField7mo.getText().equals("") 
            || jTextField8vo.getText().equals("") || jTextField9no.getText().equals("") || jTextField10mo.getText().equals("")) {
            
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
            
        } else {
            
            String[] datos = {jTextField1ro.getText(),jTextField2do.getText(),jTextField3ro.getText(),jTextField4to.getText(),jTextField5to.getText(),
                            jTextField6to.getText(),jTextField7mo.getText(),jTextField8vo.getText(),jTextField9no.getText(),jTextField10mo.getText()};
            
            definirOrden(datos);
            apuesta.calcularPuntos();
            mostrarTabla();
            JOptionPane.showMessageDialog(this, "Resultados validados");
            
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    public void mostrarTabla() {
        
        Participante participante = lista.getRaiz();
        
        for (int i = 0; i < lista.getTotalParticipantes(); i++) {
            modeloTabla.addRow(participante.getArray());
            participante = participante.getSiguiente();
            
        }
    }
    
    public void actualizarTabla() {
        
        Participante participante = lista.getRaiz();
        
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            modeloTabla.setValueAt(participante.getNombre(), i, 0);
            modeloTabla.setValueAt(participante.getMonto(), i, 1);
            modeloTabla.setValueAt(participante.getOrden()[0], i, 2);
            modeloTabla.setValueAt(participante.getOrden()[1], i, 3);
            modeloTabla.setValueAt(participante.getOrden()[2], i, 4);
            modeloTabla.setValueAt(participante.getOrden()[3], i, 5);
            modeloTabla.setValueAt(participante.getOrden()[4], i, 6);
            modeloTabla.setValueAt(participante.getOrden()[5], i, 7);
            modeloTabla.setValueAt(participante.getOrden()[6], i, 8);
            modeloTabla.setValueAt(participante.getOrden()[7], i, 9);
            modeloTabla.setValueAt(participante.getOrden()[8], i, 10);
            modeloTabla.setValueAt(participante.getOrden()[9], i, 11);
            modeloTabla.setValueAt(participante.getPuntuacionFinal(), i, 12);
            
        }

    }
    
    public void definirOrden(String[] datos) {
        
        int[] orden = new int[10];

        try {
            orden[0] = Integer.parseInt(datos[0].strip());
            orden[1] = Integer.parseInt(datos[1].strip());
            orden[2] = Integer.parseInt(datos[2].strip());
            orden[3] = Integer.parseInt(datos[3].strip());
            orden[4] = Integer.parseInt(datos[4].strip());
            orden[5] = Integer.parseInt(datos[5].strip());
            orden[6] = Integer.parseInt(datos[6].strip());
            orden[7] = Integer.parseInt(datos[7].strip());
            orden[8] = Integer.parseInt(datos[8].strip());
            orden[9] = Integer.parseInt(datos[9].strip());

        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }    

        apuesta.setOrdenCaballos(orden);
    }
    @Override
    public void dispose() {
        VistaPrincipal vp = new VistaPrincipal();
        vp.setVisible(true);
        super.dispose(); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonOrdenarNombre;
    private javax.swing.JButton jButtonOrdenarPuntos;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1ro;
    private javax.swing.JLabel jLabel2do;
    private javax.swing.JLabel jLabel3ro;
    private javax.swing.JLabel jLabel4to;
    private javax.swing.JLabel jLabel5to;
    private javax.swing.JLabel jLabel6to;
    private javax.swing.JLabel jLabel7mo;
    private javax.swing.JLabel jLabel8vo;
    private javax.swing.JLabel jLabel9no;
    private javax.swing.JLabel jLabelGanador;
    private javax.swing.JLabel jLabelInstruccion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10mo;
    private javax.swing.JTextField jTextField1Ganador;
    private javax.swing.JTextField jTextField1ro;
    private javax.swing.JTextField jTextField2do;
    private javax.swing.JTextField jTextField3ro;
    private javax.swing.JTextField jTextField4to;
    private javax.swing.JTextField jTextField5to;
    private javax.swing.JTextField jTextField6to;
    private javax.swing.JTextField jTextField7mo;
    private javax.swing.JTextField jTextField8vo;
    private javax.swing.JTextField jTextField9no;
    // End of variables declaration//GEN-END:variables
}
