
package frontend;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author CIROSS
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/frontend/images/inicio.jpg"));
        jLabelFondo.setIcon(new ImageIcon(img.getImage().getScaledInstance(this.jLabelFondo.getWidth(), this.jLabelFondo.getHeight(), Image.SCALE_SMOOTH)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonIngresoApuestas = new javax.swing.JButton();
        jButtonResultados = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuNuevaCarrera = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(0, 204, 204));
        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("APUESTAS HIPODROMO");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButtonIngresoApuestas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonIngresoApuestas.setText("Ingreso de Apuestas");
        jButtonIngresoApuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresoApuestasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresoApuestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jButtonResultados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonResultados.setText("Resultados");
        jButtonResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/images/inicio.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 760, 470));

        jMenuBar.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar.setOpaque(true);

        jMenuNuevaCarrera.setText("Archivo");

        jMenuItem1.setText("Nueva Carrera");
        jMenuNuevaCarrera.add(jMenuItem1);

        jMenuBar.add(jMenuNuevaCarrera);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresoApuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresoApuestasActionPerformed
        IngresoApuestas ingreso = new IngresoApuestas();
        ingreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonIngresoApuestasActionPerformed

    private void jButtonResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadosActionPerformed
        Resultados result = new Resultados();
        result.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonResultadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresoApuestas;
    private javax.swing.JButton jButtonResultados;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuNuevaCarrera;
    // End of variables declaration//GEN-END:variables
}
